/** All primary keys are UUIDs generated by the database. */
export type UUID = string;

/** Calendar date with no time component, ISO format YYYY-MM-DD. */
export type ISODate = string;

/** Timestamp with timezone, ISO 8601. */
export type ISODateTime = string;

/** Monetary amount in integer minor units (paise for INR). Never a float. */
export type MinorUnits = number;

/** ISO 4217 currency code, e.g. "INR". */
export type CurrencyCode = string;

/** BCP-47 language tag supported by the platform. */
export type LanguageTag = 'en' | 'te';
